#=====================================#
#  ___ _            _ _    _ _    __  #
# / __(_)_ __  _ __| (_)__(_) |_ /_/  #
# \__ \ | '  \| '_ \ | / _| |  _/ -_) #
# |___/_|_|_|_| .__/_|_\__|_|\__\___| #
#             |_|                     #
#=====================================#
#
# Note: Remplace xxx by your instance name
#
services:
  xxx:
    image: registry.simplicite.io/platform:6-latest
    restart: unless-stopped
    container_name: xxx
    environment:
      IO_PASSWORD: "_a_very_strong_password_"
      #JPDA: "true"
      #JPDA_SUSPEND: "true"
      MODULES_IMPORT_SPEC: |
        title: "Demo v6"
        modules:
          - name: "Demo"
            version: "6"
            git:
              uri: "https://github.com/simplicitesoftware/module-demo.git"
              branch: "v6"
            datasets: true
    volumes:
      - db:/usr/local/tomcat/webapps/ROOT/WEB-INF/db
      - dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xxx.rule=Host(`xxx.daz.simplicite.io`)"
      - "traefik.http.routers.xxx.entrypoints=websecure"
      - "traefik.http.routers.xxx.tls.certresolver=leresolver"
      - "traefik.http.services.xxx.loadbalancer.server.port=8443"
      # JPDA Remote debugging
      #- "traefik.tcp.routers.xxx.rule=HostSNI(`xxx.daz.simplicite.io`)"
      #- "traefik.tcp.routers.xxx.entrypoints=jpda"
      #- "traefik.tcp.routers.xxx.tls.certresolver=leresolver"
      #- "traefik.tcp.services.xxx.loadbalancer.server.port=8000"
volumes:
  db:
  dbdoc:
networks:
  proxy:
    name: proxy