services:
  demo60:
    image: registry.simplicite.io/platform:6.0-light
    restart: always
    container_name: demo60
    environment:
      MODULES_IMPORT_SPEC: |
        title: "Demo"
        modules:
          - name: "Demo"
            version: "9999"
            git: 
              uri: "https://github.com/simplicitesoftware/module-demo.git"
              branch: "v6"
            datasets: true
            unittests: true
          - name: "AIBySimplicite"
            version: "9999"
            git: 
              uri: "https://github.com/simplicitesoftware/module_ai.git"
          - name: "DemoAIAddons"
            version: "9999"
            git:
              uri: "https://github.com/simplicitesoftware/module-demo-ai.git"
          - name: "SimFeatures"
            version: "9999"
            git: 
              uri: "https://github.com/simplicitesoftware/module-SimFeatures.git"
              branch: "6.0"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo60.rule=Host(`demo60.my.domain`)"
      - "traefik.http.routers.demo60.entrypoints=websecure"
      - "traefik.http.routers.demo60.tls.certresolver=leresolver"
      - "traefik.http.services.demo60.loadbalancer.server.port=8443"
networks:
  proxy:
    name: proxy
    external: true