services:
  simplicite:
    image: registry.simplicite.io/platform:6-latest
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}
    environment:
      DEMO_NB_ORDERS: 100
      MODULES_IMPORT_SPEC: |
        title: "Demo"
        modules:
          - name: "Demo"
            version: "9999"
            git: 
              uri: "https://github.com/simplicitesoftware/module-demo.git"
              branch: "v6"
            datasets: true
            unittests: true
          - name: "SimFeatures"
            version: "9999"
            git: 
              uri: "https://github.com/simplicitesoftware/module-SimFeatures.git"
              branch: "6.1"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=leresolver"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8443"
networks:
  proxy:
    name: proxy
    external: true