#=====================================#
#  ___ _            _ _    _ _    __  #
# / __(_)_ __  _ __| (_)__(_) |_ /_/  #
# \__ \ | '  \| '_ \ | / _| |  _/ -_) #
# |___/_|_|_|_| .__/_|_\__|_|\__\___| #
#             |_|                     #
#=====================================#
services:
  demo_db:
    image: mysql:latest
    container_name: demo_db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: "Europe/Paris"
      MYSQL_ROOT_PASSWORD: "simplicite"
      MYSQL_DATABASE: "simplicite"
      MYSQL_USER: "simplicite"
      MYSQL_PASSWORD: "simplicite"
    networks:
      - proxy
    volumes:
      - db:/var/lib/mysql
  demo:
    image: registry.simplicite.io/platform:6-latest
    restart: unless-stopped
    container_name: demo
    environment:
      IO_PASSWORD: "_a_very_strong_password_"
      TOMCAT_TIMEZONE: "Europe/Paris"
      DB_SETUP: "true"
      DB_VENDOR: "mysql"
      DB_HOST: "demo_db"
      DB_USER: "simplicite"
      DB_PASSWORD: "simplicite"
      DB_NAME: "simplicite"
      DB_WAIT: 100
      DB_WAIT_INTERVAL: 10
      MODULES_IMPORT_SPEC: |
        title: "Demo v6"
        modules:
          - name: "Demo"
            version: "6"
            git:
              uri: "https://github.com/simplicitesoftware/module-demo.git"
              branch: "v6"
            datasets: true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=Host(`demo.my.domain`)"
      - "traefik.http.routers.demo.entrypoints=websecure"
      - "traefik.http.routers.demo.tls.certresolver=leresolver"
      - "traefik.http.services.demo.loadbalancer.server.port=8443"
    depends_on:
      - demo_db
volumes:
  db:
networks:
  proxy:
    name: proxy