#=====================================#
#  ___ _            _ _    _ _    __  #
# / __(_)_ __  _ __| (_)__(_) |_ /_/  #
# \__ \ | '  \| '_ \ | / _| |  _/ -_) #
# |___/_|_|_|_| .__/_|_\__|_|\__\___| #
#             |_|                     #
#=====================================#
services:
  db:
    image: mysql:latest
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: "Europe/Paris"
      MYSQL_ROOT_PASSWORD: "simplicite"
      MYSQL_DATABASE: "simplicite"
      MYSQL_USER: "simplicite"
      MYSQL_PASSWORD: "simplicite"
    networks:
      - proxy
    volumes:
      - db:/var/lib/mysql
  simplicite:
    image: registry.simplicite.io/platform:6-latest
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-app
    environment:
      IO_PASSWORD: "${IO_PASSWORD}" # Ignored unless 32 chars. Define through environment variable.
      TOMCAT_TIMEZONE: "Europe/Paris"
      DB_SETUP: "true"
      DB_VENDOR: "mysql"
      DB_HOST: "${COMPOSE_PROJECT_NAME}-db"
      DB_USER: "simplicite"
      DB_PASSWORD: "simplicite"
      DB_NAME: "simplicite"
      DB_WAIT: 100
      DB_WAIT_INTERVAL: 10
      MODULES_IMPORT_SPEC: |
        title: "${COMPOSE_PROJECT_NAME}"
        modules:
          - name: "Demo"
            git:
              uri: "https://github.com/simplicitesoftware/module-demo.git"
              branch: "v6"
            datasets: true
            unittests: true
    volumes:
      - dbdoc:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls.certresolver=leresolver"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8443"
      - "simplicite.subdomain=${COMPOSE_PROJECT_NAME}"
    depends_on:
      - "${COMPOSE_PROJECT_NAME}-db"
volumes:
  db:
  dbdoc:
networks:
  proxy:
    name: proxy
    external: true